version: "3"
services:
  math_service:
    image: math-service:latest
    ports:
      - "1337:1337"
  user_service:
    image: user-service:latest
    ports:
      - "1338:1338"
  web_service:
    image: web-service:latest
    ports:
      - "8080:8080"
    links:
      - "user_service"

