apiVersion: v1
kind: List
items:
 - apiVersion: apps/v1beta2
   kind: StatefulSet
   metadata:
     name: mongo-database
   spec:
     serviceName: "mongo-database"
     replicas: 1
     selector:
       matchLabels:
         role: mongodb
     template:
       metadata:
         labels:
          role: mongodb
          environment: test
       spec:
         terminationGracePeriodSeconds: 10
         containers:
           - name: mongo
             image: mongo
             command:
               - mongod
               - "--bind_ip=0.0.0.0"
             ports:
               - containerPort: 27017
             volumeMounts:
               - name: mongo-persistent-volume
                 mountPath: /data/db
     volumeClaimTemplates:
       - metadata:
           name: mongo-persistent-volume
         spec:
           storageClassName: manual
           accessModes: [ "ReadWriteOnce" ]
           resources:
             requests:
               storage: 1Gi

 - apiVersion: v1
   kind: Service
   metadata:
     name: mongodb
   spec:
     selector:
       role: mongodb
     ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
        nodePort: 27017
     type: NodePort