apiVersion: v1
kind: List
items:

 - apiVersion: apps/v1beta2
   kind: Deployment
   metadata:
     labels:
       app: math-service
     name: math-service
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: math-service
     template:
       metadata:
         name: math-service
         labels:
           app: math-service
       spec:
         hostname: math-service
         containers:
         - image: gapostolov/math-service
           name: math-service
           ports:
           - containerPort: 1337
         restartPolicy: Always
 - apiVersion: v1
   kind: Service
   metadata:
     name: math-service
   spec:
     selector:
       app: math-service
     ports:
      - protocol: TCP
        port: 1337
        targetPort: 1337
        nodePort: 1337
     type: NodePort

 - apiVersion: apps/v1beta2
   kind: Deployment
   metadata:
     labels:
       app: user-service
     name: user-service
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: user-service
     template:
       metadata:
         name: user-service
         labels:
           app: user-service
       spec:
         containers:
          - image: gapostolov/user-service
            name: user-service
            ports:
             - containerPort: 1338
         restartPolicy: Always

 - apiVersion: v1
   kind: Service
   metadata:
     name: user-service
   spec:
     selector:
       app: user-service
     ports:
      - protocol: TCP
        port: 1338
        targetPort: 1338
        nodePort: 1338
     type: NodePort

 - apiVersion: apps/v1beta2
   kind: Deployment
   metadata:
     labels:
       app: web-service
     name: web-service
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: web-service
     template:
       metadata:
         name: web-service
         labels:
           app: web-service
       spec:
         containers:
         - image: gapostolov/web-service:latest
           name: web-service
           ports:
           - containerPort: 8080
           imagePullPolicy: Always
         restartPolicy: Always
 - apiVersion: v1
   kind: Service
   metadata:
     name: web-service
   spec:
     selector:
       app: web-service
     ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        nodePort: 8080
     type: NodePort

 - apiVersion: apps/v1beta2
   kind: Deployment
   metadata:
     labels:
       app: ping-service
     name: ping-service
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: ping-service
     template:
       metadata:
         name: ping-service
         labels:
           app: ping-service
       spec:
         containers:
         - image: gapostolov/math-service
           name: ping-service
         restartPolicy: Always